sudo: false
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
    - 3.5

branches:
    only:
        - master

env:
    - TOXENV=py26-c,py27-c
    - TOXENV=py32-c,py33-c,py34-c,py35-c
    - TOXENV=py26-pure,py27-pure
    - TOXENV=py32-pure,py33-pure,py34-pure,py35-pure
    - TOXENV=pypy-pure,pypy3-pure

install:
    - pip install tox
    - pip install cython --install-option=--cython-with-refnanny --install-option=--no-cython-compile
    - cython --cplus msgpack/_packer.pyx msgpack/_unpacker.pyx

script: tox
